# Generated by Django 2.0.2 on 2018-09-25 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('uploadDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('file_height', models.IntegerField(default=150)),
                ('file_width', models.IntegerField(default=150)),
            ],
        ),
    ]
