# Generated by Django 2.0.2 on 2018-09-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Actual_name',
            field=models.CharField(default='Actualname', max_length=200),
        ),
    ]
