# Generated by Django 2.0.2 on 2018-09-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_actual_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file_height',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='file_width',
        ),
    ]
